name: pull request
on:
  pull_request:
  # We require PRs to be up-to-date before merging, so technically it is not needed to run the rust job
  # on main. However, for the cache to be usable in PRs we do need the job on main.
  push:
    branches: [ main ]
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Project Requirements
        run:
          pip install -r requirements.txt
      - name: Lint
        run:
          pylint src/
      - name: Unit Tests
        run:
          python -m pytest tests/
